### ISSUE TITLE
inverse-sqrt

### ISSUE THREAD

**Issue by tsulej** [Sophia-Gold/bitwise#2]
Insead of second `(Double/longBitsToDouble x)` use `(Double/doubleToRawLongBits x)`

**Comment by Sophia-Gold** [comment]
Fixed. It didn't occur to me in using unboxed math that I switched from floats to doubles, which require a different magic constant: `0x5FE6EB50C7B537A9` (via [Matthew Robertson](https://cs.uwaterloo.ca/~m32rober/rsqrt.pdf)).
